### ISSUE TITLE
Webpages Set Up

### ISSUE THREAD

**Issue by LDomadia** [LDomadia/c-546-group-19-project#1]
set up all the pages on our website
Folder Structure:
- views
     - layouts
          - main.handlebars
     - pages
          - login.handlebars
          - signup.handlebars
          - landing.handlebars
          - clothings.handlebars
          - clothingNew.handlebars
          - clothingDetails.handlebars
          - profile.handlebars 
          - statistics.handlebars
          - outfits.handlebars
          - outfitNew.handlebars
          - outfitDetails.handlebars
          - outfitGenerated.handlebars

**Comment by AlephEleven** [comment]
added handlebars, organized via:
error: error pages
medium: pages focused on adding information (i.e login, new clothing)
results: multiple result pages
single: single result pages
