### ISSUE TITLE
Set Up User Profile Page

### ISSUE THREAD

**Issue by LDomadia** [LDomadia/c-546-group-19-project#19]
- display user account info and settings
- [x] display username on top of the page
- [x] add form for bio 
- [x] add form for adding favorite stores
- [x] change password
- [x] delete account
- [x] destroy session when delete account
- [x] delete log out
- [ ] delete from clothing 

- bio and favStores will be stored in the users collections

**Comment by ColleenQue** [comment]
Set up new issue for deleting user from clothing after function is done
