### ISSUE TITLE
Create New Clothing Item

### ISSUE THREAD

**Issue by LDomadia** [LDomadia/c-546-group-19-project#5]
In data/clothes.js
- [x] create function addNewClothing()
- [x] error handing
- [x] add new clothing item to "clothes" collection

In routes/clothes.js
- [x] POST request

In views/layouts/medium/clothNew.handlebars
- [x] h1, title
- [x] form based on Figma

**Comment by AlephEleven** [comment]
finished data/clothes.js in database-seed branch, named addNewClothes
