### ISSUE TITLE
Set Up main.handlebars

### ISSUE THREAD

**Issue by LDomadia** [LDomadia/c-546-group-19-project#6]
- [x] add navigation bar in header tag
- [x] add title tag and set content to {{title}}
- [x] link stylesheet in head tag
- [x] add body tag and set content to {{{body}}}

**Comment by AlephEleven** [comment]
completed, using

{
title: "Digital Closet",
signed_in: true,
home_not_signed_in: false
}

to handle sign up status to navigation bar

**Comment by AlephEleven** [comment]
code in update-main.handlebars branch
